# コメント書いたのGsanじゃなくて石部なのでコメント内容間違ってる可能性あり
# Gsan verify済み
# 訓練用データ数
num_train: 600
# validation用データ数
num_validate: 250
# テスト用データ数
num_test: 200

# 画像の大きさ
input_sizex: 360
input_sizey: 360
# クラス数
num_class: 100
# バッチ数
Batch_num: 49
# 学習回数
learning_times: 50000
# 学習時何割くらいドロップアウトさせるか
keep_prob: 0.2
# tensorboardで何枚画像を表示するか
